# Generated by Django 4.2.6 on 2023-10-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='foodapp_pics'),
        ),
    ]
